# Generated by Django 4.1.5 on 2023-01-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_link',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_link',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
