# Generated by Django 4.1.5 on 2023-01-27 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('bio', models.TextField(blank=True, max_length=1024, null=True)),
                ('profile_image', models.ImageField(blank=True, default='user-default.png', null=True, upload_to='profiles/')),
                ('github_link', models.SlugField(blank=True, null=True)),
                ('linkedin_link', models.SlugField(blank=True, null=True)),
                ('website_link', models.SlugField(blank=True, null=True)),
                ('twitter_link', models.SlugField(blank=True, null=True)),
                ('youtube_link', models.SlugField(blank=True, null=True)),
                ('social_link', models.SlugField(blank=True, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(blank=True, max_length=64, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='application.profile')),
            ],
        ),
    ]
