# Generated by Django 4.1.5 on 2023-01-29 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_project_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectimage',
            old_name='product',
            new_name='project',
        ),
    ]
