# Generated by Django 4.1.5 on 2023-01-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_project_default_image_alter_projectimage_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='default_image',
            field=models.ImageField(default='default.png', editable=False, upload_to=''),
        ),
    ]
