# Generated by Django 4.1.5 on 2023-01-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_project_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='default_image',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
